job('First-Maven-Project-Via-DSL'){
    description("First Maven Job generated by DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm{
        git("github.com/gitrostant/MavenJenkinsFirstPorject.git", main)
    }
    triggers {
        scm('* * * * *')
    }
    steps {
    maven('clean package', 'pom.xml')
    }
    publishers {
    //archive the war file generated
    archiveArtifacts '**/*.jar'
    }
}